# onboarding.py — First-run setup
#
# Shows a tkinter GUI on Raspberry Pi OS desktop.
# Falls back to terminal prompts if running headless or tkinter is unavailable.
#
# Called by agent.py when no .env file is found, or when the user types 'setup'.

import os
import stat
from pathlib import Path

import config

ENV_FILE = Path(__file__).parent / ".env"


def write_env(api_key: str, model: str, telegram_token: str = "",
              user_id: str = "") -> None:
    """
    Write the .env configuration file.
    Sets file permissions to 600 (owner read/write only).

    user_id is used for both TELEGRAM_ALLOWED_USERS and TELEGRAM_CHAT_ID.
    Additional allowed users can be added to .env manually later.
    """
    content = f"""# Pincer Configuration
# Generated by setup. Do not share or commit this file — it contains your API keys.

OPENROUTER_API_KEY={api_key}
OPENROUTER_MODEL={model}
TELEGRAM_TOKEN={telegram_token}
TELEGRAM_ALLOWED_USERS={user_id}
TELEGRAM_CHAT_ID={user_id}
"""
    ENV_FILE.write_text(content)
    # Restrict to owner read/write only (equivalent to chmod 600)
    os.chmod(ENV_FILE, stat.S_IRUSR | stat.S_IWUSR)
    print(f"[onboarding] Configuration saved to {ENV_FILE}")


def run() -> None:
    """
    Run first-time setup. Tries the GUI, falls back to terminal prompts.
    Blocks until setup is complete and .env is written.
    """
    try:
        _run_gui()
    except Exception:
        # tkinter not available, no display, or any other GUI error
        _run_terminal()


# ---------------------------------------------------------------------------
# GUI onboarding (tkinter)
# ---------------------------------------------------------------------------

def _run_gui() -> None:
    """Show the setup window. Raises an exception if tkinter is unavailable."""
    import tkinter as tk
    from tkinter import ttk, messagebox

    root = tk.Tk()
    root.title("Pincer Setup")
    root.resizable(False, False)

    # Centre the window on screen
    root.update_idletasks()
    w, h = 620, 420
    x = (root.winfo_screenwidth()  - w) // 2
    y = (root.winfo_screenheight() - h) // 2
    root.geometry(f"{w}x{h}+{x}+{y}")

    tk.Label(
        root,
        text="Pincer Setup",
        font=("TkDefaultFont", 15, "bold"),
    ).pack(pady=(18, 2))
    tk.Label(
        root,
        text="Enter your credentials to get started.",
        fg="grey",
    ).pack(pady=(0, 10))

    frame = tk.Frame(root)
    frame.pack(fill="both", expand=True, padx=32, pady=4)
    frame.columnconfigure(1, weight=1)

    LABEL_W  = 22   # label column width in characters
    ENTRY_W  = 42   # entry field width in characters
    PAD      = {"padx": 8, "pady": 5}

    def labelled_entry(row_n, label_text, show=None, state="normal"):
        """Add a label + entry row, return the StringVar."""
        tk.Label(frame, text=label_text, anchor="w", width=LABEL_W).grid(
            row=row_n, column=0, sticky="w", **PAD
        )
        var = tk.StringVar()
        kw = {"textvariable": var, "width": ENTRY_W}
        if show:
            kw["show"] = show
        if state != "normal":
            kw["state"] = state
        entry = tk.Entry(frame, **kw)
        entry.grid(row=row_n, column=1, sticky="ew", **PAD)
        return var, entry

    # --- Row 0: OpenRouter API Key ---
    api_key_var, _ = labelled_entry(0, "OpenRouter API Key:", show="*")

    # --- Row 1: Model combobox ---
    tk.Label(frame, text="Model:", anchor="w", width=LABEL_W).grid(
        row=1, column=0, sticky="w", **PAD
    )
    model_var = tk.StringVar(value=config.POPULAR_MODELS[0])
    model_combo = ttk.Combobox(
        frame, textvariable=model_var, values=config.POPULAR_MODELS, width=ENTRY_W - 2
    )
    model_combo.grid(row=1, column=1, sticky="ew", **PAD)

    # --- Row 2: Fetch models button (own row, right-aligned) ---
    def fetch_models():
        try:
            import llm
            models = llm.get_models()
            model_combo["values"] = models
            messagebox.showinfo("Done", f"Loaded {len(models)} models from OpenRouter.")
        except Exception as e:
            messagebox.showwarning("Error", f"Could not fetch models:\n{e}\n\nUsing default list.")

    tk.Button(
        frame, text="Fetch models from OpenRouter…", command=fetch_models
    ).grid(row=2, column=1, sticky="e", padx=8, pady=(0, 6))

    # --- Divider ---
    ttk.Separator(frame, orient="horizontal").grid(
        row=3, column=0, columnspan=2, sticky="ew", pady=6
    )

    # --- Row 4: Telegram enable checkbox ---
    use_telegram = tk.BooleanVar(value=False)

    tk.Checkbutton(
        frame,
        text="Enable Telegram  (I have a bot token from @BotFather)",
        variable=use_telegram,
        command=lambda: _toggle_telegram(use_telegram, tg_widgets),
    ).grid(row=4, column=0, columnspan=2, sticky="w", padx=8, pady=(2, 0))

    # --- Row 5: Telegram token ---
    tg_token_var, tg_token_entry = labelled_entry(5, "Telegram Bot Token:", state="disabled")

    # --- Row 6: User ID ---
    tg_uid_var, tg_uid_entry = labelled_entry(6, "Your Telegram User ID:", state="disabled")

    # --- Row 7: hint (spans both columns so it never clips) ---
    tg_hint = tk.Label(
        frame,
        text="Find your user ID: open Telegram, search @userinfobot, send any message.",
        fg="grey",
        font=("TkDefaultFont", 8),
        wraplength=540,
        justify="left",
        anchor="w",
    )
    tg_hint.grid(row=7, column=0, columnspan=2, sticky="w", padx=8, pady=(0, 4))

    tg_widgets = [tg_token_entry, tg_uid_entry, tg_hint]

    # --- Save button ---
    def save_and_start():
        if not api_key_var.get().strip():
            messagebox.showwarning("Missing field", "Please enter your OpenRouter API Key.")
            return
        if use_telegram.get() and not tg_token_var.get().strip():
            messagebox.showwarning("Missing field",
                "Please enter your Telegram Bot Token, or uncheck Enable Telegram.")
            return
        write_env(
            api_key_var.get().strip(),
            model_var.get().strip(),
            tg_token_var.get().strip() if use_telegram.get() else "",
            tg_uid_var.get().strip()   if use_telegram.get() else "",
        )
        root.destroy()

    tk.Button(
        root,
        text="Save & Start",
        command=save_and_start,
        bg="#4a90d9",
        fg="white",
        font=("TkDefaultFont", 11),
        padx=16,
        pady=4,
    ).pack(pady=12)

    root.mainloop()

    # If the window was closed without saving, give a clear message and exit
    if not config.is_configured():
        print("\nSetup cancelled — no configuration was saved.")
        print("Telegram is optional — leave it disabled if you don't have a bot yet.")
        print("Restart to try again: python agent.py\n")
        raise SystemExit(0)


def _toggle_telegram(use_telegram, widgets):
    """Enable or disable Telegram entry fields based on the checkbox."""
    state  = "normal" if use_telegram.get() else "disabled"
    colour = "black"  if use_telegram.get() else "grey"
    for w in widgets:
        try:
            w.config(state=state)
        except Exception:
            w.config(fg=colour)


# ---------------------------------------------------------------------------
# Terminal onboarding (headless fallback)
# ---------------------------------------------------------------------------

def _run_terminal() -> None:
    """Interactive terminal setup for headless or SSH installs."""
    print("\n" + "=" * 52)
    print("  Pincer — First-time Setup")
    print("=" * 52 + "\n")
    print("No configuration found. Let's set you up.\n")

    # API Key
    api_key = input("OpenRouter API Key: ").strip()
    if not api_key:
        print("API key is required. Exiting.")
        raise SystemExit(1)

    # Model selection
    print("\nAvailable models:")
    for i, m in enumerate(config.POPULAR_MODELS, 1):
        print(f"  {i:2}. {m}")
    choice = input(
        f"\nSelect a number [1-{len(config.POPULAR_MODELS)}] or type a model ID: "
    ).strip()
    if choice.isdigit() and 1 <= int(choice) <= len(config.POPULAR_MODELS):
        model = config.POPULAR_MODELS[int(choice) - 1]
    elif choice:
        model = choice
    else:
        model = config.POPULAR_MODELS[0]

    # Telegram (optional)
    print("\n--- Telegram (optional — press Enter to skip) ---")
    print("    To set up Telegram later, type 'setup' inside the agent.")
    tg_token = input("Telegram Bot Token: ").strip()
    tg_uid = ""
    if tg_token:
        print("\n    Your Telegram User ID is a number, not your username.")
        print("    To find it: open Telegram, search for @userinfobot, send any message.")
        print("    It will reply with your numeric ID, e.g.  Id: 123456789")
        tg_uid = input("Your Telegram User ID: ").strip()

    write_env(api_key, model, tg_token, tg_uid)
    print("\nSetup complete. Starting Pincer...\n")
